import type { Project, DashboardStats } from '../types';

export const dashboardStats: DashboardStats = {
  totalProjects: 20,
  completedProjects: 10,
  activeProjects: 7,
  pendingPayment: 2,
  pendingDocuments: 1,
};

export const mockProjects: Project[] = [
  {
    id: '1',
    projectId: 'VAL-2026-0001',
    propertyAddress: '123 Galle Rd, Colombo 03',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Site Inspected',
    requestedDate: '2023-10-24',
    expectedCompletion: '2023-10-28',
    paymentStatus: 'Pending',
  },
  {
    id: '2',
    projectId: 'VAL-2026-0002',
    propertyAddress: '45 Kandy Rd, Kelaniya',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Awaiting Docs',
    requestedDate: '2023-10-23',
    expectedCompletion: '2023-10-29',
    paymentStatus: 'Paid',
  },
  {
    id: '3',
    projectId: 'VAL-2026-0003',
    propertyAddress: '89 Duplication Rd, Col 03',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Completed',
    requestedDate: '2023-10-20',
    expectedCompletion: '2023-10-24',
    paymentStatus: 'Paid',
  },
  {
    id: '4',
    projectId: 'VAL-2026-0004',
    propertyAddress: '12 Marine Dr, Col 04',
    applicants:["John Perera", "Nadeesha Perera"],
    status: 'Payment Pending',
    requestedDate: '2023-10-18',
    expectedCompletion: '2023-10-24',
    paymentStatus: 'Pending',
  },
  {
    id: '5',
    projectId: 'VAL-2026-0005',
    propertyAddress: '56 High Level Rd, Nugegoda',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Report Prepared',
    requestedDate: '2023-10-22',
    expectedCompletion: '2023-10-27',
    paymentStatus: 'Paid',
  },
  {
    id: '6',
    projectId: 'VAL-2026-0006',
    propertyAddress: '78 Baseline Rd, Colombo 09',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Site Inspected',
    requestedDate: '2023-10-21',
    expectedCompletion: '2023-10-26',
    paymentStatus: 'Paid',
  },
  {
    id: '7',
    projectId: 'VAL-2026-0007',
    propertyAddress: '34 Temple Rd, Maharagama',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'In Progress',
    requestedDate: '2023-10-19',
    expectedCompletion: '2023-10-25',
    paymentStatus: 'Pending',
  },
  {
    id: '8',
    projectId: 'VAL-2026-0008',
    propertyAddress: '92 Station Rd, Dehiwala',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Completed',
    requestedDate: '2023-10-17',
    expectedCompletion: '2023-10-23',
    paymentStatus: 'Paid',
  },
  {
    id: '9',
    projectId: 'VAL-2026-0009',
    propertyAddress: '15 Green Path, Colombo 07',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Awaiting Docs',
    requestedDate: '2023-10-16',
    expectedCompletion: '2023-10-22',
    paymentStatus: 'Paid',
  },
  {
    id: '10',
    projectId: 'VAL-2026-0010',
    propertyAddress: '67 Park Street, Mount Lavinia',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Report Prepared',
    requestedDate: '2023-10-15',
    expectedCompletion: '2023-10-21',
    paymentStatus: 'Pending',
  },
  {
    id: '11',
    projectId: 'VAL-2026-0011',
    propertyAddress: '101 Baudhaloka Mw, Colombo 04',
    applicants: ["John Perera", "Nadeesha Perera"],
    status: 'Site Inspected',
    requestedDate: '2023-10-14',
    expectedCompletion: '2023-10-20',
    paymentStatus: 'Paid',
  },
  {
    id: '12',
    projectId: 'VAL-2026-0012',
    propertyAddress: '23 Anderson Flats, Dehiwala',
    applicants:  ["John Perera", "Nadeesha Perera"],
    status: 'Payment Pending',
    requestedDate: '2023-10-13',
    expectedCompletion: '2023-10-19',
    paymentStatus: 'Pending',
  },
];